#############################################################################
# Makefile for building: camera_face
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  camera_face.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile camera_face.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = aarch64-xilinx-linux-gcc -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
CXX           = aarch64-xilinx-linux-g++ -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe --sysroot= -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe --sysroot= -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include -I/usr/include/opencv -I/usr/include/opencv2 -I/usr/local/include/dnndk -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtNetwork -I/usr/include/QtCore -I. -I. -I/usr/lib/mkspecs/linux-oe-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = camera_face1.0.0
DISTDIR = /home/root/clever-door/menjin-2-3/.tmp/camera_face1.0.0
LINK          = aarch64-xilinx-linux-g++ -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
LFLAGS        = --sysroot= -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/libopencv_highgui.so /usr/lib/libopencv_core.so /usr/lib/libopencv_imgproc.so /usr/lib/libopencv_imgcodecs.so /usr/lib/libopencv_videoio.so /usr/local/lib/libdputils.so /usr/local/lib/libn2cube.so /usr/local/lib/libhineon.so ./model/dpu_resnet50.elf ./model/dpu_ultra96v2_DenseBox_360x640_2304.elf -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGLESv2 -lpthread 
AR            = cqs
RANLIB        = 
SED           = sed
STRIP         = aarch64-xilinx-linux-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		workthread.cpp \
		tcp_to_seve.cpp \
		testtem.cpp qrc_persondatas.cpp \
		qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_workthread.cpp \
		moc_tcp_to_seve.cpp
OBJECTS       = main.o \
		mainwindow.o \
		workthread.o \
		tcp_to_seve.o \
		testtem.o \
		qrc_persondatas.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_workthread.o \
		moc_tcp_to_seve.o
DIST          = /usr/lib/mkspecs/features/spec_pre.prf \
		/usr/lib/mkspecs/common/unix.conf \
		/usr/lib/mkspecs/common/linux.conf \
		/usr/lib/mkspecs/common/sanitize.conf \
		/usr/lib/mkspecs/common/gcc-base.conf \
		/usr/lib/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/mkspecs/common/g++-base.conf \
		/usr/lib/mkspecs/common/g++-unix.conf \
		/usr/lib/mkspecs/oe-device-extra.pri \
		/usr/lib/mkspecs/qdevice.pri \
		/usr/lib/mkspecs/features/device_config.prf \
		/usr/lib/mkspecs/qconfig.pri \
		/usr/lib/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/lib/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/lib/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_systeminfo.pri \
		/usr/lib/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/lib/mkspecs/features/qt_functions.prf \
		/usr/lib/mkspecs/features/qt_config.prf \
		/usr/lib/mkspecs/linux-oe-g++/qmake.conf \
		/usr/lib/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/mkspecs/features/exclusive_builds.prf \
		/usr/lib/mkspecs/features/toolchain.prf \
		/usr/lib/mkspecs/features/default_pre.prf \
		/usr/lib/mkspecs/features/resolve_config.prf \
		/usr/lib/mkspecs/features/default_post.prf \
		/usr/lib/mkspecs/features/warn_on.prf \
		/usr/lib/mkspecs/features/qt.prf \
		/usr/lib/mkspecs/features/resources.prf \
		/usr/lib/mkspecs/features/moc.prf \
		/usr/lib/mkspecs/features/unix/opengl.prf \
		/usr/lib/mkspecs/features/uic.prf \
		/usr/lib/mkspecs/features/unix/thread.prf \
		/usr/lib/mkspecs/features/qmake_use.prf \
		/usr/lib/mkspecs/features/file_copies.prf \
		/usr/lib/mkspecs/features/testcase_targets.prf \
		/usr/lib/mkspecs/features/exceptions.prf \
		/usr/lib/mkspecs/features/yacc.prf \
		/usr/lib/mkspecs/features/lex.prf \
		camera_face.pro mainwindow.h \
		workthread.h \
		tcp_to_seve.h \
		testtem.h main.cpp \
		mainwindow.cpp \
		workthread.cpp \
		tcp_to_seve.cpp \
		testtem.cpp
QMAKE_TARGET  = camera_face
DESTDIR       = 
TARGET        = camera_face


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: camera_face.pro /usr/lib/mkspecs/linux-oe-g++/qmake.conf /usr/lib/mkspecs/features/spec_pre.prf \
		/usr/lib/mkspecs/common/unix.conf \
		/usr/lib/mkspecs/common/linux.conf \
		/usr/lib/mkspecs/common/sanitize.conf \
		/usr/lib/mkspecs/common/gcc-base.conf \
		/usr/lib/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/mkspecs/common/g++-base.conf \
		/usr/lib/mkspecs/common/g++-unix.conf \
		/usr/lib/mkspecs/oe-device-extra.pri \
		/usr/lib/mkspecs/qdevice.pri \
		/usr/lib/mkspecs/features/device_config.prf \
		/usr/lib/mkspecs/qconfig.pri \
		/usr/lib/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/lib/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/lib/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_systeminfo.pri \
		/usr/lib/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/lib/mkspecs/features/qt_functions.prf \
		/usr/lib/mkspecs/features/qt_config.prf \
		/usr/lib/mkspecs/linux-oe-g++/qmake.conf \
		/usr/lib/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/mkspecs/features/exclusive_builds.prf \
		/usr/lib/mkspecs/features/toolchain.prf \
		/usr/lib/mkspecs/features/default_pre.prf \
		/usr/lib/mkspecs/features/resolve_config.prf \
		/usr/lib/mkspecs/features/default_post.prf \
		/usr/lib/mkspecs/features/warn_on.prf \
		/usr/lib/mkspecs/features/qt.prf \
		/usr/lib/mkspecs/features/resources.prf \
		/usr/lib/mkspecs/features/moc.prf \
		/usr/lib/mkspecs/features/unix/opengl.prf \
		/usr/lib/mkspecs/features/uic.prf \
		/usr/lib/mkspecs/features/unix/thread.prf \
		/usr/lib/mkspecs/features/qmake_use.prf \
		/usr/lib/mkspecs/features/file_copies.prf \
		/usr/lib/mkspecs/features/testcase_targets.prf \
		/usr/lib/mkspecs/features/exceptions.prf \
		/usr/lib/mkspecs/features/yacc.prf \
		/usr/lib/mkspecs/features/lex.prf \
		camera_face.pro \
		persondatas.qrc \
		images.qrc \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Network.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile camera_face.pro
/usr/lib/mkspecs/features/spec_pre.prf:
/usr/lib/mkspecs/common/unix.conf:
/usr/lib/mkspecs/common/linux.conf:
/usr/lib/mkspecs/common/sanitize.conf:
/usr/lib/mkspecs/common/gcc-base.conf:
/usr/lib/mkspecs/common/gcc-base-unix.conf:
/usr/lib/mkspecs/common/g++-base.conf:
/usr/lib/mkspecs/common/g++-unix.conf:
/usr/lib/mkspecs/oe-device-extra.pri:
/usr/lib/mkspecs/qdevice.pri:
/usr/lib/mkspecs/features/device_config.prf:
/usr/lib/mkspecs/qconfig.pri:
/usr/lib/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/mkspecs/modules/qt_lib_core.pri:
/usr/lib/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/mkspecs/modules/qt_lib_network.pri:
/usr/lib/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/mkspecs/modules/qt_lib_publishsubscribe.pri:
/usr/lib/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/usr/lib/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/mkspecs/modules/qt_lib_script.pri:
/usr/lib/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_serviceframework.pri:
/usr/lib/mkspecs/modules/qt_lib_serviceframework_private.pri:
/usr/lib/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/mkspecs/modules/qt_lib_systeminfo.pri:
/usr/lib/mkspecs/modules/qt_lib_systeminfo_private.pri:
/usr/lib/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/lib/mkspecs/features/qt_functions.prf:
/usr/lib/mkspecs/features/qt_config.prf:
/usr/lib/mkspecs/linux-oe-g++/qmake.conf:
/usr/lib/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/mkspecs/features/exclusive_builds.prf:
/usr/lib/mkspecs/features/toolchain.prf:
/usr/lib/mkspecs/features/default_pre.prf:
/usr/lib/mkspecs/features/resolve_config.prf:
/usr/lib/mkspecs/features/default_post.prf:
/usr/lib/mkspecs/features/warn_on.prf:
/usr/lib/mkspecs/features/qt.prf:
/usr/lib/mkspecs/features/resources.prf:
/usr/lib/mkspecs/features/moc.prf:
/usr/lib/mkspecs/features/unix/opengl.prf:
/usr/lib/mkspecs/features/uic.prf:
/usr/lib/mkspecs/features/unix/thread.prf:
/usr/lib/mkspecs/features/qmake_use.prf:
/usr/lib/mkspecs/features/file_copies.prf:
/usr/lib/mkspecs/features/testcase_targets.prf:
/usr/lib/mkspecs/features/exceptions.prf:
/usr/lib/mkspecs/features/yacc.prf:
/usr/lib/mkspecs/features/lex.prf:
camera_face.pro:
persondatas.qrc:
images.qrc:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Network.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile camera_face.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents persondatas.qrc images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h workthread.h tcp_to_seve.h testtem.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp workthread.cpp tcp_to_seve.cpp testtem.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_persondatas.cpp qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_persondatas.cpp qrc_images.cpp
qrc_persondatas.cpp: persondatas.qrc \
		/usr/bin/rcc \
		related_file/personDatas.txt
	/usr/bin/rcc -name persondatas persondatas.qrc -o qrc_persondatas.cpp

qrc_images.cpp: images.qrc \
		/usr/bin/rcc \
		images/titleLabel.png \
		images/backimage.jpg \
		images/icon.jpg
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/mkspecs/features/data/dummy.cpp
	aarch64-xilinx-linux-g++ -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -pipe --sysroot= -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_workthread.cpp moc_tcp_to_seve.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_workthread.cpp moc_tcp_to_seve.cpp
moc_mainwindow.cpp: workthread.h \
		tcp_to_seve.h \
		testtem.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/root/clever-door/menjin-2-3/moc_predefs.h -I/usr/lib/mkspecs/linux-oe-g++ -I/home/root/clever-door/menjin-2-3 -I/usr/include -I/usr/include/opencv -I/usr/include/opencv2 -I/usr/local/include/dnndk -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/8.2.0 -I/usr/include/c++/8.2.0/aarch64-xilinx-linux -I/usr/include/c++/8.2.0/backward -I/usr/lib/gcc/aarch64-xilinx-linux/8.2.0/include -I/usr/local/include -I/usr/lib/gcc/aarch64-xilinx-linux/8.2.0/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_workthread.cpp: workthread.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/root/clever-door/menjin-2-3/moc_predefs.h -I/usr/lib/mkspecs/linux-oe-g++ -I/home/root/clever-door/menjin-2-3 -I/usr/include -I/usr/include/opencv -I/usr/include/opencv2 -I/usr/local/include/dnndk -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/8.2.0 -I/usr/include/c++/8.2.0/aarch64-xilinx-linux -I/usr/include/c++/8.2.0/backward -I/usr/lib/gcc/aarch64-xilinx-linux/8.2.0/include -I/usr/local/include -I/usr/lib/gcc/aarch64-xilinx-linux/8.2.0/include-fixed -I/usr/include workthread.h -o moc_workthread.cpp

moc_tcp_to_seve.cpp: tcp_to_seve.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/root/clever-door/menjin-2-3/moc_predefs.h -I/usr/lib/mkspecs/linux-oe-g++ -I/home/root/clever-door/menjin-2-3 -I/usr/include -I/usr/include/opencv -I/usr/include/opencv2 -I/usr/local/include/dnndk -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/8.2.0 -I/usr/include/c++/8.2.0/aarch64-xilinx-linux -I/usr/include/c++/8.2.0/backward -I/usr/lib/gcc/aarch64-xilinx-linux/8.2.0/include -I/usr/local/include -I/usr/lib/gcc/aarch64-xilinx-linux/8.2.0/include-fixed -I/usr/include tcp_to_seve.h -o moc_tcp_to_seve.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/bin/uic
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		workthread.h \
		tcp_to_seve.h \
		testtem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		workthread.h \
		tcp_to_seve.h \
		testtem.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

workthread.o: workthread.cpp workthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workthread.o workthread.cpp

tcp_to_seve.o: tcp_to_seve.cpp tcp_to_seve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcp_to_seve.o tcp_to_seve.cpp

testtem.o: testtem.cpp testtem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testtem.o testtem.cpp

qrc_persondatas.o: qrc_persondatas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_persondatas.o qrc_persondatas.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_workthread.o: moc_workthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_workthread.o moc_workthread.cpp

moc_tcp_to_seve.o: moc_tcp_to_seve.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcp_to_seve.o moc_tcp_to_seve.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

